version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/develop.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
  flask:
    env_file:
      - .env
    build: 
      context: .
      target: test
    ports:
      - "5000:5000"
    volumes:
      - ./flask/:/web/
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--debugger", "--reload"]
