openapi: 3.0.3
info:
  title: python-mob-programing - OpenAPI 3.0
  version: 0.1.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost
tags:
  - name: hello
    description: hello world
  - name: health
    description: health check
  - name: shorten
    description: shorten url
paths:
  /:
    get:
      tags:
        - hello
      summary: hello world flask
      description: hello world endpoint
      operationId: getHelloWorld
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: "Hello, Docker! Here are the users: user_name"
  /health:
    get:
      tags:
        - health
      summary: health check
      description: health check
      operationId: getHealthCheck
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: "OK"
                
  /shorten-url:
    post:
      tags:
        - shorten
      summary: hello world flask
      description: shorten url
      operationId: createShortenUrl
      requestBody:
        content:
          applicatoin/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  nullable: false
                keyword:
                  type: string
                  nullable: true
      
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: "https://example.com"
